### ISSUE TITLE
Build issue with backend

### ISSUE THREAD

**Issue by erhant** [erhant/leet-assistant#5]
When we do `bun run build` which runs the following script:

```sh
bun build ./src/index.ts --outdir ./dist --target bun
```

we get the following rather interesting error:

```sh
❯ bun run ./dist/index.js
77044 |     var cplx = type === "Complex";
77045 |     var zero = big ? bignumber(0) : cplx ? complex2(0) : 0;
77046 |     var one = big ? bignumber(1) : cplx ? complex2(1) : 1;
77047 |     var uniqueValues = [];
77048 |     var multiplicities = [];
77049 |     for (var λ of values) {
        ^
SyntaxError: Invalid character '\u00bb'
      at <parse> (/Users/erhant/leet-assistant/backend/dist/index.js:77049:1)
```

I shall try and reproduce this error & create an issue on Elysia / Bun.

**Comment by erhant** [comment]
Another issue seems to be due to LangChain. When we build with the following:

```sh
bun build ./src/index.ts --outdir ./dist --target node --minifiy --sourcemap=external
```

and then run the output file with:

```sh
node ./dist/index.js
```

we get the following error:

```sh
❯ node ./dist/index.js
file:///Users/erhant/leet-assistant/backend/dist/index.js:34909
class BaseStringPromptTemplate extends BasePromptTemplate {
                                       ^

ReferenceError: Cannot access 'BasePromptTemplate' before initialization
    at file:///Users/erhant/leet-assistant/backend/dist/index.js:34909:40
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

**Comment by erhant** [comment]
aint got time for this Bun stuff, closing issue
